<a href="https://colab.research.google.com/github/emon4075/PyTorch-For-Deep-Learning/blob/master/PyTorch_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [33]:
# Import the PyTorch library, essential for tensor operations and building neural networks in deep learning.
import torch

# Basic Mathematical Operations

In [34]:
# Initialize two 3x3 tensors with random integer values.
# Tensors are the fundamental data structures in deep learning, holding data like input features or model weights.
tensor_a = torch.randint(1, 10, (3, 3))
tensor_b = torch.randint(8, 15, (3, 3))

In [35]:
# Display the contents of the initialized tensors.
# This is crucial for debugging and understanding the state of data within a deep learning model.
print(tensor_a)
print(tensor_b)

tensor([[9, 9, 4],
        [2, 4, 3],
        [1, 4, 2]])
tensor([[11, 10, 10],
        [ 8, 13, 11],
        [13, 14, 10]])


## Addition

In [36]:
# Performs element-wise addition of two tensors.
# Element-wise operations are fundamental in deep learning, used for operations like adding biases to activations.
tensor_a + tensor_b

tensor([[20, 19, 14],
        [10, 17, 14],
        [14, 18, 12]])

In [37]:
# Another method for element-wise addition using the torch.add function.
# This explicit function can be useful for clarity or when specific arguments are needed.
torch.add(tensor_a, tensor_b)

tensor([[20, 19, 14],
        [10, 17, 14],
        [14, 18, 12]])

In [38]:
# Display the current state of tensor_a.
# Important to observe if in-place operations have modified the tensor's values, which is common in deep learning for memory efficiency.
tensor_a

tensor([[9, 9, 4],
        [2, 4, 3],
        [1, 4, 2]])

In [39]:
# Performs in-place element-wise addition (note the underscore `_`).
# This operation modifies tensor_a directly, saving memory, a common practice in optimizing deep learning models.
tensor_a.add_ (tensor_b)

tensor([[20, 19, 14],
        [10, 17, 14],
        [14, 18, 12]])

In [40]:
# Display tensor_a again to confirm its updated value after the in-place addition.
# Verifying state changes is vital when working with mutable tensors in deep learning.
tensor_a

tensor([[20, 19, 14],
        [10, 17, 14],
        [14, 18, 12]])

## Subtraction

In [41]:
# Performs element-wise subtraction of two tensors.
# Subtraction operations can be used in loss functions or to compute differences between model outputs and targets.
tensor_a - tensor_b

tensor([[9, 9, 4],
        [2, 4, 3],
        [1, 4, 2]])

In [42]:
# Another method for element-wise subtraction using the torch.sub function.
torch.sub(tensor_a, tensor_b)

tensor([[9, 9, 4],
        [2, 4, 3],
        [1, 4, 2]])

## Multiplication

In [43]:
# Performs element-wise multiplication of two tensors.
# Element-wise multiplication is used in various deep learning contexts, such as gating mechanisms or attention.
tensor_a * tensor_b

tensor([[220, 190, 140],
        [ 80, 221, 154],
        [182, 252, 120]])

In [44]:
# Another method for element-wise multiplication using the torch.mul function.
torch.mul(tensor_a, tensor_b)

tensor([[220, 190, 140],
        [ 80, 221, 154],
        [182, 252, 120]])

## Division

In [45]:
# Performs element-wise division of two tensors.
# Division operations can appear in normalization layers or when computing ratios.
tensor_a / tensor_b

tensor([[1.8182, 1.9000, 1.4000],
        [1.2500, 1.3077, 1.2727],
        [1.0769, 1.2857, 1.2000]])

In [46]:
# Another method for element-wise division using the torch.div function.
torch.div(tensor_a, tensor_b)

tensor([[1.8182, 1.9000, 1.4000],
        [1.2500, 1.3077, 1.2727],
        [1.0769, 1.2857, 1.2000]])

## Remainder

In [47]:
# Performs element-wise remainder (modulo) operation.
# While less common in core neural network computations, modulo can be used in specialized data preprocessing or feature engineering.
tensor_a % tensor_b

tensor([[9, 9, 4],
        [2, 4, 3],
        [1, 4, 2]])

In [48]:
# Another method for element-wise remainder using the torch.remainder function.
torch.remainder(tensor_a, tensor_b)

tensor([[9, 9, 4],
        [2, 4, 3],
        [1, 4, 2]])