<a href="https://colab.research.google.com/github/emon4075/PyTorch-For-Deep-Learning/blob/master/PyTorch_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [22]:
import numpy as np # NumPy is often used for data preprocessing and numerical operations before converting to tensors.
import torch # PyTorch is a widely used deep learning framework; tensors are its fundamental data structure.

# Lists in Python

In [23]:
list_1d = [1, 2, 3, 4, 5, 6]
print(list_1d) # Python lists can hold raw data before it's converted into more efficient structures like tensors for deep learning models.

[1, 2, 3, 4, 5, 6]


In [24]:
list_2d = [
    [1, 2, 3, 4],
    [3, 2, 1.8, 4]
]
print(list_2d) # A 2D list can represent a simple dataset or a batch of inputs before conversion to a tensor for model processing.

[[1, 2, 3, 4], [3, 2, 1.8, 4]]


In [25]:
print(type(list_1d))
print(type(list_2d)) # Understanding data types is essential in deep learning; incorrect types can lead to errors or performance issues, especially when working with tensors on GPUs.

<class 'list'>
<class 'list'>


# NumPy Array in Python

In [26]:
np_array_1d = np.array([1, 2, 4, 5]) # NumPy arrays are efficient for numerical operations and are often an intermediate step for converting data to PyTorch tensors.
print(np_array_1d)

[1 2 4 5]


In [27]:
np_array_2d = np.array(list_2d) # A 2D NumPy array often represents a batch of samples or features in a dataset.
print(np_array_2d)
print(np_array_2d.dtype) # The data type (dtype) is crucial; deep learning models often prefer float32 for inputs due to memory and computation efficiency.

[[1.  2.  3.  4. ]
 [3.  2.  1.8 4. ]]
float64


# Tensors in PyTorch

In [28]:
tensor_1d = torch.tensor([1, 2, 3]) # PyTorch tensors are the core data structure for deep learning, holding model inputs, outputs, and parameters.
print(tensor_1d)
print(tensor_1d.dtype) # The tensor's dtype is important for operations and memory management; int64 is often used for indices or labels, while float32/float64 for numerical data.

tensor([1, 2, 3])
torch.int64


In [29]:
tensor_2d = torch.tensor(np_array_2d) # Converting NumPy arrays to PyTorch tensors is a common step to prepare data for deep learning models.
print(tensor_2d)
print(tensor_2d.dtype) # A 2D tensor can represent a batch of input data (e.g., images or tabular data) or feature maps within a neural network. The dtype must match model expectations.

tensor([[1.0000, 2.0000, 3.0000, 4.0000],
        [3.0000, 2.0000, 1.8000, 4.0000]], dtype=torch.float64)
torch.float64
