<a href="https://colab.research.google.com/github/emon4075/PyTorch-For-Deep-Learning/blob/master/PyTorch_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [47]:
import torch # Import the torch library for tensor operations

# Reshape & View

In [48]:
rand_tensor = torch.randint(1, 13, [1, 12]) # Create a 1D tensor with 12 random integers between 1 and 12
print(rand_tensor) # Print the generated tensor

tensor([[12,  7, 10,  1,  4, 12, 11,  2,  2,  8,  2,  6]])


In [49]:
tensor_2d_reshape = rand_tensor.reshape(-1, 3) # Reshape the 1D tensor into a 2D tensor with 3 columns, inferring the number of rows
print(tensor_2d_reshape) # Print the reshaped tensor
print(tensor_2d_reshape.shape) # Print the shape of the reshaped tensor

tensor([[12,  7, 10],
        [ 1,  4, 12],
        [11,  2,  2],
        [ 8,  2,  6]])
torch.Size([4, 3])


In [50]:
tensor_2d_view = rand_tensor.view(-1, 3) # Create a view of the 1D tensor as a 2D tensor with 3 columns, inferring the number of rows
print(tensor_2d_view) # Print the viewed tensor
print(tensor_2d_view.shape) # Print the shape of the viewed tensor

tensor([[12,  7, 10],
        [ 1,  4, 12],
        [11,  2,  2],
        [ 8,  2,  6]])
torch.Size([4, 3])


# Slicing

In [51]:
random_tensor = torch.rand((4, 5)) + 1 # Create a 4x5 tensor with random floats between 1 and 2
print(random_tensor) # Print the generated tensor

tensor([[1.3586, 1.3521, 1.3345, 1.0694, 1.9477],
        [1.7100, 1.3000, 1.0591, 1.5719, 1.8522],
        [1.8458, 1.1042, 1.7313, 1.4276, 1.8314],
        [1.7294, 1.4585, 1.5518, 1.1515, 1.6223]])


In [52]:
print(random_tensor[:2, :]) # Print the first two rows and all columns of the tensor

tensor([[1.3586, 1.3521, 1.3345, 1.0694, 1.9477],
        [1.7100, 1.3000, 1.0591, 1.5719, 1.8522]])


In [53]:
print(random_tensor[3:, :2]) # Print the last row and the first two columns of the tensor

tensor([[1.7294, 1.4585]])
